import { BORDER, ROUNDED } from "@/ui/globals";
import { cva } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

const item = cva(
  twMerge(
    `flex
  cursor-pointer
  items-center
  justify-center
  h-8
  w-8
  [&_>_svg]:h-4
  [&_>_svg]:w-4
  outline-none 
  data-[disabled]:pointer-events-none
  border-transparent`,
    ROUNDED,
    BORDER,
  ),
  {
    defaultVariants: {
      color: "neutral",
    },
    variants: {
      color: {
        brand: `text-brand-900
    hover:bg-brand-50
    hover:text-brand-900
    hover:border-brand-500
    focus:bg-brand-50
    focus:text-brand-900
    focus:border-brand-500
    data-[state=on]:bg-brand-50
    data-[disabled]:text-brand-700
    data-[state=on]:text-brand-900
    data-[state=on]:border-brand-500
    hover:data-[state=on]:bg-brand-200
    focus:data-[state=on]:bg-brand-200
    dark:text-brand-200
    dark:hover:bg-brand-900
    dark:hover:text-brand-100 
    dark:hover:border-brand-600 
    dark:focus:bg-brand-900 
    dark:focus:text-brand-100 
    dark:focus:border-brand-600
    dark:data-[state=on]:bg-brand-900 
    dark:data-[disabled]:text-brand-400
    dark:data-[state=on]:text-brand-100
    dark:data-[state=on]:border-brand-600
    dark:hover:data-[state=on]:bg-brand-800
    dark:focus:data-[state=on]:bg-brand-800`,
        slate: `text-slate-900
    hover:bg-slate-50
    hover:text-slate-900
    hover:border-slate-500
    focus:bg-slate-50
    focus:text-slate-900
    focus:border-slate-500
    data-[state=on]:bg-slate-50
    data-[disabled]:text-slate-700
    data-[state=on]:text-slate-900
    data-[state=on]:border-slate-500
    hover:data-[state=on]:bg-slate-200
    focus:data-[state=on]:bg-slate-200
    dark:text-slate-200
    dark:hover:bg-slate-900
    dark:hover:text-slate-100 
    dark:hover:border-slate-600 
    dark:focus:bg-slate-900 
    dark:focus:text-slate-100 
    dark:focus:border-slate-600
    dark:data-[state=on]:bg-slate-900 
    dark:data-[disabled]:text-slate-400
    dark:data-[state=on]:text-slate-100
    dark:data-[state=on]:border-slate-600
    dark:hover:data-[state=on]:bg-slate-800
    dark:focus:data-[state=on]:bg-slate-800`,
        gray: `text-gray-900
    hover:bg-gray-50
    hover:text-gray-900
    hover:border-gray-500
    focus:bg-gray-50
    focus:text-gray-900
    focus:border-gray-500
    data-[state=on]:bg-gray-50
    data-[disabled]:text-gray-700
    data-[state=on]:text-gray-900
    data-[state=on]:border-gray-500
    hover:data-[state=on]:bg-gray-200
    focus:data-[state=on]:bg-gray-200
    dark:text-gray-200
    dark:hover:bg-gray-900
    dark:hover:text-gray-100 
    dark:hover:border-gray-600 
    dark:focus:bg-gray-900 
    dark:focus:text-gray-100 
    dark:focus:border-gray-600
    dark:data-[state=on]:bg-gray-900 
    dark:data-[disabled]:text-gray-400
    dark:data-[state=on]:text-gray-100
    dark:data-[state=on]:border-gray-600
    dark:hover:data-[state=on]:bg-gray-800
    dark:focus:data-[state=on]:bg-gray-800`,
        zinc: `text-zinc-900
    hover:bg-zinc-50
    hover:text-zinc-900
    hover:border-zinc-500
    focus:bg-zinc-50
    focus:text-zinc-900
    focus:border-zinc-500
    data-[state=on]:bg-zinc-50
    data-[disabled]:text-zinc-700
    data-[state=on]:text-zinc-900
    data-[state=on]:border-zinc-500
    hover:data-[state=on]:bg-zinc-200
    focus:data-[state=on]:bg-zinc-200
    dark:text-zinc-200
    dark:hover:bg-zinc-900
    dark:hover:text-zinc-100 
    dark:hover:border-zinc-600 
    dark:focus:bg-zinc-900 
    dark:focus:text-zinc-100 
    dark:focus:border-zinc-600
    dark:data-[state=on]:bg-zinc-900 
    dark:data-[disabled]:text-zinc-400
    dark:data-[state=on]:text-zinc-100
    dark:data-[state=on]:border-zinc-600
    dark:hover:data-[state=on]:bg-zinc-800
    dark:focus:data-[state=on]:bg-zinc-800`,
        neutral: `text-neutral-900
    hover:bg-neutral-50
    hover:text-neutral-900
    hover:border-neutral-500
    focus:bg-neutral-50
    focus:text-neutral-900
    focus:border-neutral-500
    data-[state=on]:bg-neutral-50
    data-[disabled]:text-neutral-700
    data-[state=on]:text-neutral-900
    data-[state=on]:border-neutral-500
    hover:data-[state=on]:bg-neutral-200
    focus:data-[state=on]:bg-neutral-200
    dark:text-neutral-200
    dark:hover:bg-neutral-900
    dark:hover:text-neutral-100 
    dark:hover:border-neutral-600 
    dark:focus:bg-neutral-900 
    dark:focus:text-neutral-100 
    dark:focus:border-neutral-600
    dark:data-[state=on]:bg-neutral-900 
    dark:data-[disabled]:text-neutral-400
    dark:data-[state=on]:text-neutral-100
    dark:data-[state=on]:border-neutral-600
    dark:hover:data-[state=on]:bg-neutral-800
    dark:focus:data-[state=on]:bg-neutral-800`,
        stone: `text-stone-900
    hover:bg-stone-50
    hover:text-stone-900
    hover:border-stone-500
    focus:bg-stone-50
    focus:text-stone-900
    focus:border-stone-500
    data-[state=on]:bg-stone-50
    data-[disabled]:text-stone-700
    data-[state=on]:text-stone-900
    data-[state=on]:border-stone-500
    hover:data-[state=on]:bg-stone-200
    focus:data-[state=on]:bg-stone-200
    dark:text-stone-200
    dark:hover:bg-stone-900
    dark:hover:text-stone-100 
    dark:hover:border-stone-600 
    dark:focus:bg-stone-900 
    dark:focus:text-stone-100 
    dark:focus:border-stone-600
    dark:data-[state=on]:bg-stone-900 
    dark:data-[disabled]:text-stone-400
    dark:data-[state=on]:text-stone-100
    dark:data-[state=on]:border-stone-600
    dark:hover:data-[state=on]:bg-stone-800
    dark:focus:data-[state=on]:bg-stone-800`,
        red: `text-red-900
    hover:bg-red-50
    hover:text-red-900
    hover:border-red-500
    focus:bg-red-50
    focus:text-red-900
    focus:border-red-500
    data-[state=on]:bg-red-50
    data-[disabled]:text-red-700
    data-[state=on]:text-red-900
    data-[state=on]:border-red-500
    hover:data-[state=on]:bg-red-200
    focus:data-[state=on]:bg-red-200
    dark:text-red-200
    dark:hover:bg-red-900
    dark:hover:text-red-100 
    dark:hover:border-red-600 
    dark:focus:bg-red-900 
    dark:focus:text-red-100 
    dark:focus:border-red-600
    dark:data-[state=on]:bg-red-900 
    dark:data-[disabled]:text-red-400
    dark:data-[state=on]:text-red-100
    dark:data-[state=on]:border-red-600
    dark:hover:data-[state=on]:bg-red-800
    dark:focus:data-[state=on]:bg-red-800`,
        orange: `text-orange-900
    hover:bg-orange-50
    hover:text-orange-900
    hover:border-orange-500
    focus:bg-orange-50
    focus:text-orange-900
    focus:border-orange-500
    data-[state=on]:bg-orange-50
    data-[disabled]:text-orange-700
    data-[state=on]:text-orange-900
    data-[state=on]:border-orange-500
    hover:data-[state=on]:bg-orange-200
    focus:data-[state=on]:bg-orange-200
    dark:text-orange-200
    dark:hover:bg-orange-900
    dark:hover:text-orange-100 
    dark:hover:border-orange-600 
    dark:focus:bg-orange-900 
    dark:focus:text-orange-100 
    dark:focus:border-orange-600
    dark:data-[state=on]:bg-orange-900 
    dark:data-[disabled]:text-orange-400
    dark:data-[state=on]:text-orange-100
    dark:data-[state=on]:border-orange-600
    dark:hover:data-[state=on]:bg-orange-800
    dark:focus:data-[state=on]:bg-orange-800`,
        amber: `text-amber-900
    hover:bg-amber-50
    hover:text-amber-900
    hover:border-amber-500
    focus:bg-amber-50
    focus:text-amber-900
    focus:border-amber-500
    data-[state=on]:bg-amber-50
    data-[disabled]:text-amber-700
    data-[state=on]:text-amber-900
    data-[state=on]:border-amber-500
    hover:data-[state=on]:bg-amber-200
    focus:data-[state=on]:bg-amber-200
    dark:text-amber-200
    dark:hover:bg-amber-900
    dark:hover:text-amber-100 
    dark:hover:border-amber-600 
    dark:focus:bg-amber-900 
    dark:focus:text-amber-100 
    dark:focus:border-amber-600
    dark:data-[state=on]:bg-amber-900 
    dark:data-[disabled]:text-amber-400
    dark:data-[state=on]:text-amber-100
    dark:data-[state=on]:border-amber-600
    dark:hover:data-[state=on]:bg-amber-800
    dark:focus:data-[state=on]:bg-amber-800`,
        yellow: `text-yellow-900
    hover:bg-yellow-50
    hover:text-yellow-900
    hover:border-yellow-500
    focus:bg-yellow-50
    focus:text-yellow-900
    focus:border-yellow-500
    data-[state=on]:bg-yellow-50
    data-[disabled]:text-yellow-700
    data-[state=on]:text-yellow-900
    data-[state=on]:border-yellow-500
    hover:data-[state=on]:bg-yellow-200
    focus:data-[state=on]:bg-yellow-200
    dark:text-yellow-200
    dark:hover:bg-yellow-900
    dark:hover:text-yellow-100 
    dark:hover:border-yellow-600 
    dark:focus:bg-yellow-900 
    dark:focus:text-yellow-100 
    dark:focus:border-yellow-600
    dark:data-[state=on]:bg-yellow-900 
    dark:data-[disabled]:text-yellow-400
    dark:data-[state=on]:text-yellow-100
    dark:data-[state=on]:border-yellow-600
    dark:hover:data-[state=on]:bg-yellow-800
    dark:focus:data-[state=on]:bg-yellow-800`,
        lime: `text-lime-900
    hover:bg-lime-50
    hover:text-lime-900
    hover:border-lime-500
    focus:bg-lime-50
    focus:text-lime-900
    focus:border-lime-500
    data-[state=on]:bg-lime-50
    data-[disabled]:text-lime-700
    data-[state=on]:text-lime-900
    data-[state=on]:border-lime-500
    hover:data-[state=on]:bg-lime-200
    focus:data-[state=on]:bg-lime-200
    dark:text-lime-200
    dark:hover:bg-lime-900
    dark:hover:text-lime-100 
    dark:hover:border-lime-600 
    dark:focus:bg-lime-900 
    dark:focus:text-lime-100 
    dark:focus:border-lime-600
    dark:data-[state=on]:bg-lime-900 
    dark:data-[disabled]:text-lime-400
    dark:data-[state=on]:text-lime-100
    dark:data-[state=on]:border-lime-600
    dark:hover:data-[state=on]:bg-lime-800
    dark:focus:data-[state=on]:bg-lime-800`,
        green: `text-green-900
    hover:bg-green-50
    hover:text-green-900
    hover:border-green-500
    focus:bg-green-50
    focus:text-green-900
    focus:border-green-500
    data-[state=on]:bg-green-50
    data-[disabled]:text-green-700
    data-[state=on]:text-green-900
    data-[state=on]:border-green-500
    hover:data-[state=on]:bg-green-200
    focus:data-[state=on]:bg-green-200
    dark:text-green-200
    dark:hover:bg-green-900
    dark:hover:text-green-100 
    dark:hover:border-green-600 
    dark:focus:bg-green-900 
    dark:focus:text-green-100 
    dark:focus:border-green-600
    dark:data-[state=on]:bg-green-900 
    dark:data-[disabled]:text-green-400
    dark:data-[state=on]:text-green-100
    dark:data-[state=on]:border-green-600
    dark:hover:data-[state=on]:bg-green-800
    dark:focus:data-[state=on]:bg-green-800`,
        emerald: `text-emerald-900
    hover:bg-emerald-50
    hover:text-emerald-900
    hover:border-emerald-500
    focus:bg-emerald-50
    focus:text-emerald-900
    focus:border-emerald-500
    data-[state=on]:bg-emerald-50
    data-[disabled]:text-emerald-700
    data-[state=on]:text-emerald-900
    data-[state=on]:border-emerald-500
    hover:data-[state=on]:bg-emerald-200
    focus:data-[state=on]:bg-emerald-200
    dark:text-emerald-200
    dark:hover:bg-emerald-900
    dark:hover:text-emerald-100 
    dark:hover:border-emerald-600 
    dark:focus:bg-emerald-900 
    dark:focus:text-emerald-100 
    dark:focus:border-emerald-600
    dark:data-[state=on]:bg-emerald-900 
    dark:data-[disabled]:text-emerald-400
    dark:data-[state=on]:text-emerald-100
    dark:data-[state=on]:border-emerald-600
    dark:hover:data-[state=on]:bg-emerald-800
    dark:focus:data-[state=on]:bg-emerald-800`,
        teal: `text-teal-900
    hover:bg-teal-50
    hover:text-teal-900
    hover:border-teal-500
    focus:bg-teal-50
    focus:text-teal-900
    focus:border-teal-500
    data-[state=on]:bg-teal-50
    data-[disabled]:text-teal-700
    data-[state=on]:text-teal-900
    data-[state=on]:border-teal-500
    hover:data-[state=on]:bg-teal-200
    focus:data-[state=on]:bg-teal-200
    dark:text-teal-200
    dark:hover:bg-teal-900
    dark:hover:text-teal-100 
    dark:hover:border-teal-600 
    dark:focus:bg-teal-900 
    dark:focus:text-teal-100 
    dark:focus:border-teal-600
    dark:data-[state=on]:bg-teal-900 
    dark:data-[disabled]:text-teal-400
    dark:data-[state=on]:text-teal-100
    dark:data-[state=on]:border-teal-600
    dark:hover:data-[state=on]:bg-teal-800
    dark:focus:data-[state=on]:bg-teal-800`,
        cyan: `text-cyan-900
    hover:bg-cyan-50
    hover:text-cyan-900
    hover:border-cyan-500
    focus:bg-cyan-50
    focus:text-cyan-900
    focus:border-cyan-500
    data-[state=on]:bg-cyan-50
    data-[disabled]:text-cyan-700
    data-[state=on]:text-cyan-900
    data-[state=on]:border-cyan-500
    hover:data-[state=on]:bg-cyan-200
    focus:data-[state=on]:bg-cyan-200
    dark:text-cyan-200
    dark:hover:bg-cyan-900
    dark:hover:text-cyan-100 
    dark:hover:border-cyan-600 
    dark:focus:bg-cyan-900 
    dark:focus:text-cyan-100 
    dark:focus:border-cyan-600
    dark:data-[state=on]:bg-cyan-900 
    dark:data-[disabled]:text-cyan-400
    dark:data-[state=on]:text-cyan-100
    dark:data-[state=on]:border-cyan-600
    dark:hover:data-[state=on]:bg-cyan-800
    dark:focus:data-[state=on]:bg-cyan-800`,
        sky: `text-sky-900
    hover:bg-sky-50
    hover:text-sky-900
    hover:border-sky-500
    focus:bg-sky-50
    focus:text-sky-900
    focus:border-sky-500
    data-[state=on]:bg-sky-50
    data-[disabled]:text-sky-700
    data-[state=on]:text-sky-900
    data-[state=on]:border-sky-500
    hover:data-[state=on]:bg-sky-200
    focus:data-[state=on]:bg-sky-200
    dark:text-sky-200
    dark:hover:bg-sky-900
    dark:hover:text-sky-100 
    dark:hover:border-sky-600 
    dark:focus:bg-sky-900 
    dark:focus:text-sky-100 
    dark:focus:border-sky-600
    dark:data-[state=on]:bg-sky-900 
    dark:data-[disabled]:text-sky-400
    dark:data-[state=on]:text-sky-100
    dark:data-[state=on]:border-sky-600
    dark:hover:data-[state=on]:bg-sky-800
    dark:focus:data-[state=on]:bg-sky-800`,
        blue: `text-blue-900
    hover:bg-blue-50
    hover:text-blue-900
    hover:border-blue-500
    focus:bg-blue-50
    focus:text-blue-900
    focus:border-blue-500
    data-[state=on]:bg-blue-50
    data-[disabled]:text-blue-700
    data-[state=on]:text-blue-900
    data-[state=on]:border-blue-500
    hover:data-[state=on]:bg-blue-200
    focus:data-[state=on]:bg-blue-200
    dark:text-blue-200
    dark:hover:bg-blue-900
    dark:hover:text-blue-100 
    dark:hover:border-blue-600 
    dark:focus:bg-blue-900 
    dark:focus:text-blue-100 
    dark:focus:border-blue-600
    dark:data-[state=on]:bg-blue-900 
    dark:data-[disabled]:text-blue-400
    dark:data-[state=on]:text-blue-100
    dark:data-[state=on]:border-blue-600
    dark:hover:data-[state=on]:bg-blue-800
    dark:focus:data-[state=on]:bg-blue-800`,
        indigo: `text-indigo-900
    hover:bg-indigo-50
    hover:text-indigo-900
    hover:border-indigo-500
    focus:bg-indigo-50
    focus:text-indigo-900
    focus:border-indigo-500
    data-[state=on]:bg-indigo-50
    data-[disabled]:text-indigo-700
    data-[state=on]:text-indigo-900
    data-[state=on]:border-indigo-500
    hover:data-[state=on]:bg-indigo-200
    focus:data-[state=on]:bg-indigo-200
    dark:text-indigo-200
    dark:hover:bg-indigo-900
    dark:hover:text-indigo-100 
    dark:hover:border-indigo-600 
    dark:focus:bg-indigo-900 
    dark:focus:text-indigo-100 
    dark:focus:border-indigo-600
    dark:data-[state=on]:bg-indigo-900 
    dark:data-[disabled]:text-indigo-400
    dark:data-[state=on]:text-indigo-100
    dark:data-[state=on]:border-indigo-600
    dark:hover:data-[state=on]:bg-indigo-800
    dark:focus:data-[state=on]:bg-indigo-800`,
        violet: `text-violet-900
    hover:bg-violet-50
    hover:text-violet-900
    hover:border-violet-500
    focus:bg-violet-50
    focus:text-violet-900
    focus:border-violet-500
    data-[state=on]:bg-violet-50
    data-[disabled]:text-violet-700
    data-[state=on]:text-violet-900
    data-[state=on]:border-violet-500
    hover:data-[state=on]:bg-violet-200
    focus:data-[state=on]:bg-violet-200
    dark:text-violet-200
    dark:hover:bg-violet-900
    dark:hover:text-violet-100 
    dark:hover:border-violet-600 
    dark:focus:bg-violet-900 
    dark:focus:text-violet-100 
    dark:focus:border-violet-600
    dark:data-[state=on]:bg-violet-900 
    dark:data-[disabled]:text-violet-400
    dark:data-[state=on]:text-violet-100
    dark:data-[state=on]:border-violet-600
    dark:hover:data-[state=on]:bg-violet-800
    dark:focus:data-[state=on]:bg-violet-800`,
        purple: `text-purple-900
    hover:bg-purple-50
    hover:text-purple-900
    hover:border-purple-500
    focus:bg-purple-50
    focus:text-purple-900
    focus:border-purple-500
    data-[state=on]:bg-purple-50
    data-[disabled]:text-purple-700
    data-[state=on]:text-purple-900
    data-[state=on]:border-purple-500
    hover:data-[state=on]:bg-purple-200
    focus:data-[state=on]:bg-purple-200
    dark:text-purple-200
    dark:hover:bg-purple-900
    dark:hover:text-purple-100 
    dark:hover:border-purple-600 
    dark:focus:bg-purple-900 
    dark:focus:text-purple-100 
    dark:focus:border-purple-600
    dark:data-[state=on]:bg-purple-900 
    dark:data-[disabled]:text-purple-400
    dark:data-[state=on]:text-purple-100
    dark:data-[state=on]:border-purple-600
    dark:hover:data-[state=on]:bg-purple-800
    dark:focus:data-[state=on]:bg-purple-800`,
        fuchsia: `text-fuchsia-900
    hover:bg-fuchsia-50
    hover:text-fuchsia-900
    hover:border-fuchsia-500
    focus:bg-fuchsia-50
    focus:text-fuchsia-900
    focus:border-fuchsia-500
    data-[state=on]:bg-fuchsia-50
    data-[disabled]:text-fuchsia-700
    data-[state=on]:text-fuchsia-900
    data-[state=on]:border-fuchsia-500
    hover:data-[state=on]:bg-fuchsia-200
    focus:data-[state=on]:bg-fuchsia-200
    dark:text-fuchsia-200
    dark:hover:bg-fuchsia-900
    dark:hover:text-fuchsia-100 
    dark:hover:border-fuchsia-600 
    dark:focus:bg-fuchsia-900 
    dark:focus:text-fuchsia-100 
    dark:focus:border-fuchsia-600
    dark:data-[state=on]:bg-fuchsia-900 
    dark:data-[disabled]:text-fuchsia-400
    dark:data-[state=on]:text-fuchsia-100
    dark:data-[state=on]:border-fuchsia-600
    dark:hover:data-[state=on]:bg-fuchsia-800
    dark:focus:data-[state=on]:bg-fuchsia-800`,
        pink: `text-pink-900
    hover:bg-pink-50
    hover:text-pink-900
    hover:border-pink-500
    focus:bg-pink-50
    focus:text-pink-900
    focus:border-pink-500
    data-[state=on]:bg-pink-50
    data-[disabled]:text-pink-700
    data-[state=on]:text-pink-900
    data-[state=on]:border-pink-500
    hover:data-[state=on]:bg-pink-200
    focus:data-[state=on]:bg-pink-200
    dark:text-pink-200
    dark:hover:bg-pink-900
    dark:hover:text-pink-100 
    dark:hover:border-pink-600 
    dark:focus:bg-pink-900 
    dark:focus:text-pink-100 
    dark:focus:border-pink-600
    dark:data-[state=on]:bg-pink-900 
    dark:data-[disabled]:text-pink-400
    dark:data-[state=on]:text-pink-100
    dark:data-[state=on]:border-pink-600
    dark:hover:data-[state=on]:bg-pink-800
    dark:focus:data-[state=on]:bg-pink-800`,
        rose: `text-rose-900
    hover:bg-rose-50
    hover:text-rose-900
    hover:border-rose-500
    focus:bg-rose-50
    focus:text-rose-900
    focus:border-rose-500
    data-[state=on]:bg-rose-50
    data-[disabled]:text-rose-700
    data-[state=on]:text-rose-900
    data-[state=on]:border-rose-500
    hover:data-[state=on]:bg-rose-200
    focus:data-[state=on]:bg-rose-200
    dark:text-rose-200
    dark:hover:bg-rose-900
    dark:hover:text-rose-100 
    dark:hover:border-rose-600 
    dark:focus:bg-rose-900 
    dark:focus:text-rose-100 
    dark:focus:border-rose-600
    dark:data-[state=on]:bg-rose-900 
    dark:data-[disabled]:text-rose-400
    dark:data-[state=on]:text-rose-100
    dark:data-[state=on]:border-rose-600
    dark:hover:data-[state=on]:bg-rose-800
    dark:focus:data-[state=on]:bg-rose-800`,
        "white-black": `text-neutral-900
    hover:bg-neutral-50
    hover:text-neutral-900
    hover:border-neutral-500
    focus:bg-neutral-50
    focus:text-neutral-900
    focus:border-neutral-500
    data-[state=on]:bg-neutral-50
    data-[disabled]:text-neutral-700
    data-[state=on]:text-neutral-900
    data-[state=on]:border-neutral-500
    hover:data-[state=on]:bg-neutral-200
    focus:data-[state=on]:bg-neutral-200
    dark:text-neutral-200
    dark:hover:bg-neutral-900
    dark:hover:text-neutral-100 
    dark:hover:border-neutral-600 
    dark:focus:bg-neutral-900 
    dark:focus:text-neutral-100 
    dark:focus:border-neutral-600
    dark:data-[state=on]:bg-neutral-900 
    dark:data-[disabled]:text-neutral-400
    dark:data-[state=on]:text-neutral-100
    dark:data-[state=on]:border-neutral-600
    dark:hover:data-[state=on]:bg-neutral-800
    dark:focus:data-[state=on]:bg-neutral-800`,
      },
    },
  },
);

export { item };
