import { BORDER, ROUNDED } from "@/ui/globals";
import { cva } from "class-variance-authority";
import { twMerge } from "tailwind-merge";

const trigger = cva(
  twMerge(
    `flex
  cursor-pointer
  select-none
  items-center 
  justify-center
  p-2
  px-3
  text-sm
  py-1.5
  outline-none
  border-transparent
  m-px
  data-[disabled]:pointer-events-none`,
    ROUNDED,
    BORDER,
  ),
  {
    defaultVariants: {
      color: "neutral",
    },
    variants: {
      color: {
        brand: `text-brand-900
            hover:bg-brand-100
            hover:text-brand-900
            hover:border-brand-500
            focus:bg-brand-100
            focus:text-brand-900
            focus:border-brand-500
            data-[state=open]:bg-brand-100
            data-[disabled]:text-brand-700
            data-[state=open]:text-brand-900
            data-[state=open]:border-brand-500
            hover:data-[state=open]:bg-brand-200
            focus:data-[state=open]:bg-brand-200
            dark:text-brand-200
            dark:hover:bg-brand-900
            dark:hover:text-brand-100 
            dark:hover:border-brand-600 
            dark:focus:bg-brand-900 
            dark:focus:text-brand-100 
            dark:focus:border-brand-600
            dark:data-[state=open]:bg-brand-900 
            dark:data-[disabled]:text-brand-400
            dark:data-[state=open]:text-brand-100
            dark:data-[state=open]:border-brand-600
            dark:hover:data-[state=open]:bg-brand-800
            dark:focus:data-[state=open]:bg-brand-800`,
        slate: `text-slate-900
            hover:bg-slate-100
            hover:text-slate-900
            hover:border-slate-500
            focus:bg-slate-100
            focus:text-slate-900
            focus:border-slate-500
            data-[state=open]:bg-slate-100
            data-[disabled]:text-slate-700
            data-[state=open]:text-slate-900
            data-[state=open]:border-slate-500
            hover:data-[state=open]:bg-slate-200
            focus:data-[state=open]:bg-slate-200
            dark:text-slate-200
            dark:hover:bg-slate-900
            dark:hover:text-slate-100 
            dark:hover:border-slate-600 
            dark:focus:bg-slate-900 
            dark:focus:text-slate-100 
            dark:focus:border-slate-600
            dark:data-[state=open]:bg-slate-900 
            dark:data-[disabled]:text-slate-400
            dark:data-[state=open]:text-slate-100
            dark:data-[state=open]:border-slate-600
            dark:hover:data-[state=open]:bg-slate-800
            dark:focus:data-[state=open]:bg-slate-800`,
        gray: `text-gray-900
            hover:bg-gray-100
            hover:text-gray-900
            hover:border-gray-500
            focus:bg-gray-100
            focus:text-gray-900
            focus:border-gray-500
            data-[state=open]:bg-gray-100
            data-[disabled]:text-gray-700
            data-[state=open]:text-gray-900
            data-[state=open]:border-gray-500
            hover:data-[state=open]:bg-gray-200
            focus:data-[state=open]:bg-gray-200
            dark:text-gray-200
            dark:hover:bg-gray-900
            dark:hover:text-gray-100 
            dark:hover:border-gray-600 
            dark:focus:bg-gray-900 
            dark:focus:text-gray-100 
            dark:focus:border-gray-600
            dark:data-[state=open]:bg-gray-900 
            dark:data-[disabled]:text-gray-400
            dark:data-[state=open]:text-gray-100
            dark:data-[state=open]:border-gray-600
            dark:hover:data-[state=open]:bg-gray-800
            dark:focus:data-[state=open]:bg-gray-800`,
        zinc: `text-zinc-900
            hover:bg-zinc-100
            hover:text-zinc-900
            hover:border-zinc-500
            focus:bg-zinc-100
            focus:text-zinc-900
            focus:border-zinc-500
            data-[state=open]:bg-zinc-100
            data-[disabled]:text-zinc-700
            data-[state=open]:text-zinc-900
            data-[state=open]:border-zinc-500
            hover:data-[state=open]:bg-zinc-200
            focus:data-[state=open]:bg-zinc-200
            dark:text-zinc-200
            dark:hover:bg-zinc-900
            dark:hover:text-zinc-100 
            dark:hover:border-zinc-600 
            dark:focus:bg-zinc-900 
            dark:focus:text-zinc-100 
            dark:focus:border-zinc-600
            dark:data-[state=open]:bg-zinc-900 
            dark:data-[disabled]:text-zinc-400
            dark:data-[state=open]:text-zinc-100
            dark:data-[state=open]:border-zinc-600
            dark:hover:data-[state=open]:bg-zinc-800
            dark:focus:data-[state=open]:bg-zinc-800`,
        neutral: `text-neutral-900
            hover:bg-neutral-100
            hover:text-neutral-900
            hover:border-neutral-500
            focus:bg-neutral-100
            focus:text-neutral-900
            focus:border-neutral-500
            data-[state=open]:bg-neutral-100
            data-[disabled]:text-neutral-700
            data-[state=open]:text-neutral-900
            data-[state=open]:border-neutral-500
            hover:data-[state=open]:bg-neutral-200
            focus:data-[state=open]:bg-neutral-200
            dark:text-neutral-200
            dark:hover:bg-neutral-900
            dark:hover:text-neutral-100 
            dark:hover:border-neutral-600 
            dark:focus:bg-neutral-900 
            dark:focus:text-neutral-100 
            dark:focus:border-neutral-600
            dark:data-[state=open]:bg-neutral-900 
            dark:data-[disabled]:text-neutral-400
            dark:data-[state=open]:text-neutral-100
            dark:data-[state=open]:border-neutral-600
            dark:hover:data-[state=open]:bg-neutral-800
            dark:focus:data-[state=open]:bg-neutral-800`,
        stone: `text-stone-900
            hover:bg-stone-100
            hover:text-stone-900
            hover:border-stone-500
            focus:bg-stone-100
            focus:text-stone-900
            focus:border-stone-500
            data-[state=open]:bg-stone-100
            data-[disabled]:text-stone-700
            data-[state=open]:text-stone-900
            data-[state=open]:border-stone-500
            hover:data-[state=open]:bg-stone-200
            focus:data-[state=open]:bg-stone-200
            dark:text-stone-200
            dark:hover:bg-stone-900
            dark:hover:text-stone-100 
            dark:hover:border-stone-600 
            dark:focus:bg-stone-900 
            dark:focus:text-stone-100 
            dark:focus:border-stone-600
            dark:data-[state=open]:bg-stone-900 
            dark:data-[disabled]:text-stone-400
            dark:data-[state=open]:text-stone-100
            dark:data-[state=open]:border-stone-600
            dark:hover:data-[state=open]:bg-stone-800
            dark:focus:data-[state=open]:bg-stone-800`,
        red: `text-red-900
            hover:bg-red-100
            hover:text-red-900
            hover:border-red-500
            focus:bg-red-100
            focus:text-red-900
            focus:border-red-500
            data-[state=open]:bg-red-100
            data-[disabled]:text-red-700
            data-[state=open]:text-red-900
            data-[state=open]:border-red-500
            hover:data-[state=open]:bg-red-200
            focus:data-[state=open]:bg-red-200
            dark:text-red-200
            dark:hover:bg-red-900
            dark:hover:text-red-100 
            dark:hover:border-red-600 
            dark:focus:bg-red-900 
            dark:focus:text-red-100 
            dark:focus:border-red-600
            dark:data-[state=open]:bg-red-900 
            dark:data-[disabled]:text-red-400
            dark:data-[state=open]:text-red-100
            dark:data-[state=open]:border-red-600
            dark:hover:data-[state=open]:bg-red-800
            dark:focus:data-[state=open]:bg-red-800`,
        orange: `text-orange-900
            hover:bg-orange-100
            hover:text-orange-900
            hover:border-orange-500
            focus:bg-orange-100
            focus:text-orange-900
            focus:border-orange-500
            data-[state=open]:bg-orange-100
            data-[disabled]:text-orange-700
            data-[state=open]:text-orange-900
            data-[state=open]:border-orange-500
            hover:data-[state=open]:bg-orange-200
            focus:data-[state=open]:bg-orange-200
            dark:text-orange-200
            dark:hover:bg-orange-900
            dark:hover:text-orange-100 
            dark:hover:border-orange-600 
            dark:focus:bg-orange-900 
            dark:focus:text-orange-100 
            dark:focus:border-orange-600
            dark:data-[state=open]:bg-orange-900 
            dark:data-[disabled]:text-orange-400
            dark:data-[state=open]:text-orange-100
            dark:data-[state=open]:border-orange-600
            dark:hover:data-[state=open]:bg-orange-800
            dark:focus:data-[state=open]:bg-orange-800`,
        amber: `text-amber-900
            hover:bg-amber-100
            hover:text-amber-900
            hover:border-amber-500
            focus:bg-amber-100
            focus:text-amber-900
            focus:border-amber-500
            data-[state=open]:bg-amber-100
            data-[disabled]:text-amber-700
            data-[state=open]:text-amber-900
            data-[state=open]:border-amber-500
            hover:data-[state=open]:bg-amber-200
            focus:data-[state=open]:bg-amber-200
            dark:text-amber-200
            dark:hover:bg-amber-900
            dark:hover:text-amber-100 
            dark:hover:border-amber-600 
            dark:focus:bg-amber-900 
            dark:focus:text-amber-100 
            dark:focus:border-amber-600
            dark:data-[state=open]:bg-amber-900 
            dark:data-[disabled]:text-amber-400
            dark:data-[state=open]:text-amber-100
            dark:data-[state=open]:border-amber-600
            dark:hover:data-[state=open]:bg-amber-800
            dark:focus:data-[state=open]:bg-amber-800`,
        yellow: `text-yellow-900
            hover:bg-yellow-100
            hover:text-yellow-900
            hover:border-yellow-500
            focus:bg-yellow-100
            focus:text-yellow-900
            focus:border-yellow-500
            data-[state=open]:bg-yellow-100
            data-[disabled]:text-yellow-700
            data-[state=open]:text-yellow-900
            data-[state=open]:border-yellow-500
            hover:data-[state=open]:bg-yellow-200
            focus:data-[state=open]:bg-yellow-200
            dark:text-yellow-200
            dark:hover:bg-yellow-900
            dark:hover:text-yellow-100 
            dark:hover:border-yellow-600 
            dark:focus:bg-yellow-900 
            dark:focus:text-yellow-100 
            dark:focus:border-yellow-600
            dark:data-[state=open]:bg-yellow-900 
            dark:data-[disabled]:text-yellow-400
            dark:data-[state=open]:text-yellow-100
            dark:data-[state=open]:border-yellow-600
            dark:hover:data-[state=open]:bg-yellow-800
            dark:focus:data-[state=open]:bg-yellow-800`,
        lime: `text-lime-900
            hover:bg-lime-100
            hover:text-lime-900
            hover:border-lime-500
            focus:bg-lime-100
            focus:text-lime-900
            focus:border-lime-500
            data-[state=open]:bg-lime-100
            data-[disabled]:text-lime-700
            data-[state=open]:text-lime-900
            data-[state=open]:border-lime-500
            hover:data-[state=open]:bg-lime-200
            focus:data-[state=open]:bg-lime-200
            dark:text-lime-200
            dark:hover:bg-lime-900
            dark:hover:text-lime-100 
            dark:hover:border-lime-600 
            dark:focus:bg-lime-900 
            dark:focus:text-lime-100 
            dark:focus:border-lime-600
            dark:data-[state=open]:bg-lime-900 
            dark:data-[disabled]:text-lime-400
            dark:data-[state=open]:text-lime-100
            dark:data-[state=open]:border-lime-600
            dark:hover:data-[state=open]:bg-lime-800
            dark:focus:data-[state=open]:bg-lime-800`,
        green: `text-green-900
            hover:bg-green-100
            hover:text-green-900
            hover:border-green-500
            focus:bg-green-100
            focus:text-green-900
            focus:border-green-500
            data-[state=open]:bg-green-100
            data-[disabled]:text-green-700
            data-[state=open]:text-green-900
            data-[state=open]:border-green-500
            hover:data-[state=open]:bg-green-200
            focus:data-[state=open]:bg-green-200
            dark:text-green-200
            dark:hover:bg-green-900
            dark:hover:text-green-100 
            dark:hover:border-green-600 
            dark:focus:bg-green-900 
            dark:focus:text-green-100 
            dark:focus:border-green-600
            dark:data-[state=open]:bg-green-900 
            dark:data-[disabled]:text-green-400
            dark:data-[state=open]:text-green-100
            dark:data-[state=open]:border-green-600
            dark:hover:data-[state=open]:bg-green-800
            dark:focus:data-[state=open]:bg-green-800`,
        emerald: `text-emerald-900
            hover:bg-emerald-100
            hover:text-emerald-900
            hover:border-emerald-500
            focus:bg-emerald-100
            focus:text-emerald-900
            focus:border-emerald-500
            data-[state=open]:bg-emerald-100
            data-[disabled]:text-emerald-700
            data-[state=open]:text-emerald-900
            data-[state=open]:border-emerald-500
            hover:data-[state=open]:bg-emerald-200
            focus:data-[state=open]:bg-emerald-200
            dark:text-emerald-200
            dark:hover:bg-emerald-900
            dark:hover:text-emerald-100 
            dark:hover:border-emerald-600 
            dark:focus:bg-emerald-900 
            dark:focus:text-emerald-100 
            dark:focus:border-emerald-600
            dark:data-[state=open]:bg-emerald-900 
            dark:data-[disabled]:text-emerald-400
            dark:data-[state=open]:text-emerald-100
            dark:data-[state=open]:border-emerald-600
            dark:hover:data-[state=open]:bg-emerald-800
            dark:focus:data-[state=open]:bg-emerald-800`,
        teal: `text-teal-900
            hover:bg-teal-100
            hover:text-teal-900
            hover:border-teal-500
            focus:bg-teal-100
            focus:text-teal-900
            focus:border-teal-500
            data-[state=open]:bg-teal-100
            data-[disabled]:text-teal-700
            data-[state=open]:text-teal-900
            data-[state=open]:border-teal-500
            hover:data-[state=open]:bg-teal-200
            focus:data-[state=open]:bg-teal-200
            dark:text-teal-200
            dark:hover:bg-teal-900
            dark:hover:text-teal-100 
            dark:hover:border-teal-600 
            dark:focus:bg-teal-900 
            dark:focus:text-teal-100 
            dark:focus:border-teal-600
            dark:data-[state=open]:bg-teal-900 
            dark:data-[disabled]:text-teal-400
            dark:data-[state=open]:text-teal-100
            dark:data-[state=open]:border-teal-600
            dark:hover:data-[state=open]:bg-teal-800
            dark:focus:data-[state=open]:bg-teal-800`,
        cyan: `text-cyan-900
            hover:bg-cyan-100
            hover:text-cyan-900
            hover:border-cyan-500
            focus:bg-cyan-100
            focus:text-cyan-900
            focus:border-cyan-500
            data-[state=open]:bg-cyan-100
            data-[disabled]:text-cyan-700
            data-[state=open]:text-cyan-900
            data-[state=open]:border-cyan-500
            hover:data-[state=open]:bg-cyan-200
            focus:data-[state=open]:bg-cyan-200
            dark:text-cyan-200
            dark:hover:bg-cyan-900
            dark:hover:text-cyan-100 
            dark:hover:border-cyan-600 
            dark:focus:bg-cyan-900 
            dark:focus:text-cyan-100 
            dark:focus:border-cyan-600
            dark:data-[state=open]:bg-cyan-900 
            dark:data-[disabled]:text-cyan-400
            dark:data-[state=open]:text-cyan-100
            dark:data-[state=open]:border-cyan-600
            dark:hover:data-[state=open]:bg-cyan-800
            dark:focus:data-[state=open]:bg-cyan-800`,
        sky: `text-sky-900
            hover:bg-sky-100
            hover:text-sky-900
            hover:border-sky-500
            focus:bg-sky-100
            focus:text-sky-900
            focus:border-sky-500
            data-[state=open]:bg-sky-100
            data-[disabled]:text-sky-700
            data-[state=open]:text-sky-900
            data-[state=open]:border-sky-500
            hover:data-[state=open]:bg-sky-200
            focus:data-[state=open]:bg-sky-200
            dark:text-sky-200
            dark:hover:bg-sky-900
            dark:hover:text-sky-100 
            dark:hover:border-sky-600 
            dark:focus:bg-sky-900 
            dark:focus:text-sky-100 
            dark:focus:border-sky-600
            dark:data-[state=open]:bg-sky-900 
            dark:data-[disabled]:text-sky-400
            dark:data-[state=open]:text-sky-100
            dark:data-[state=open]:border-sky-600
            dark:hover:data-[state=open]:bg-sky-800
            dark:focus:data-[state=open]:bg-sky-800`,
        blue: `text-blue-900
            hover:bg-blue-100
            hover:text-blue-900
            hover:border-blue-500
            focus:bg-blue-100
            focus:text-blue-900
            focus:border-blue-500
            data-[state=open]:bg-blue-100
            data-[disabled]:text-blue-700
            data-[state=open]:text-blue-900
            data-[state=open]:border-blue-500
            hover:data-[state=open]:bg-blue-200
            focus:data-[state=open]:bg-blue-200
            dark:text-blue-200
            dark:hover:bg-blue-900
            dark:hover:text-blue-100 
            dark:hover:border-blue-600 
            dark:focus:bg-blue-900 
            dark:focus:text-blue-100 
            dark:focus:border-blue-600
            dark:data-[state=open]:bg-blue-900 
            dark:data-[disabled]:text-blue-400
            dark:data-[state=open]:text-blue-100
            dark:data-[state=open]:border-blue-600
            dark:hover:data-[state=open]:bg-blue-800
            dark:focus:data-[state=open]:bg-blue-800`,
        indigo: `text-indigo-900
            hover:bg-indigo-100
            hover:text-indigo-900
            hover:border-indigo-500
            focus:bg-indigo-100
            focus:text-indigo-900
            focus:border-indigo-500
            data-[state=open]:bg-indigo-100
            data-[disabled]:text-indigo-700
            data-[state=open]:text-indigo-900
            data-[state=open]:border-indigo-500
            hover:data-[state=open]:bg-indigo-200
            focus:data-[state=open]:bg-indigo-200
            dark:text-indigo-200
            dark:hover:bg-indigo-900
            dark:hover:text-indigo-100 
            dark:hover:border-indigo-600 
            dark:focus:bg-indigo-900 
            dark:focus:text-indigo-100 
            dark:focus:border-indigo-600
            dark:data-[state=open]:bg-indigo-900 
            dark:data-[disabled]:text-indigo-400
            dark:data-[state=open]:text-indigo-100
            dark:data-[state=open]:border-indigo-600
            dark:hover:data-[state=open]:bg-indigo-800
            dark:focus:data-[state=open]:bg-indigo-800`,
        violet: `text-violet-900
            hover:bg-violet-100
            hover:text-violet-900
            hover:border-violet-500
            focus:bg-violet-100
            focus:text-violet-900
            focus:border-violet-500
            data-[state=open]:bg-violet-100
            data-[disabled]:text-violet-700
            data-[state=open]:text-violet-900
            data-[state=open]:border-violet-500
            hover:data-[state=open]:bg-violet-200
            focus:data-[state=open]:bg-violet-200
            dark:text-violet-200
            dark:hover:bg-violet-900
            dark:hover:text-violet-100 
            dark:hover:border-violet-600 
            dark:focus:bg-violet-900 
            dark:focus:text-violet-100 
            dark:focus:border-violet-600
            dark:data-[state=open]:bg-violet-900 
            dark:data-[disabled]:text-violet-400
            dark:data-[state=open]:text-violet-100
            dark:data-[state=open]:border-violet-600
            dark:hover:data-[state=open]:bg-violet-800
            dark:focus:data-[state=open]:bg-violet-800`,
        purple: `text-purple-900
            hover:bg-purple-100
            hover:text-purple-900
            hover:border-purple-500
            focus:bg-purple-100
            focus:text-purple-900
            focus:border-purple-500
            data-[state=open]:bg-purple-100
            data-[disabled]:text-purple-700
            data-[state=open]:text-purple-900
            data-[state=open]:border-purple-500
            hover:data-[state=open]:bg-purple-200
            focus:data-[state=open]:bg-purple-200
            dark:text-purple-200
            dark:hover:bg-purple-900
            dark:hover:text-purple-100 
            dark:hover:border-purple-600 
            dark:focus:bg-purple-900 
            dark:focus:text-purple-100 
            dark:focus:border-purple-600
            dark:data-[state=open]:bg-purple-900 
            dark:data-[disabled]:text-purple-400
            dark:data-[state=open]:text-purple-100
            dark:data-[state=open]:border-purple-600
            dark:hover:data-[state=open]:bg-purple-800
            dark:focus:data-[state=open]:bg-purple-800`,
        fuchsia: `text-fuchsia-900
            hover:bg-fuchsia-100
            hover:text-fuchsia-900
            hover:border-fuchsia-500
            focus:bg-fuchsia-100
            focus:text-fuchsia-900
            focus:border-fuchsia-500
            data-[state=open]:bg-fuchsia-100
            data-[disabled]:text-fuchsia-700
            data-[state=open]:text-fuchsia-900
            data-[state=open]:border-fuchsia-500
            hover:data-[state=open]:bg-fuchsia-200
            focus:data-[state=open]:bg-fuchsia-200
            dark:text-fuchsia-200
            dark:hover:bg-fuchsia-900
            dark:hover:text-fuchsia-100 
            dark:hover:border-fuchsia-600 
            dark:focus:bg-fuchsia-900 
            dark:focus:text-fuchsia-100 
            dark:focus:border-fuchsia-600
            dark:data-[state=open]:bg-fuchsia-900 
            dark:data-[disabled]:text-fuchsia-400
            dark:data-[state=open]:text-fuchsia-100
            dark:data-[state=open]:border-fuchsia-600
            dark:hover:data-[state=open]:bg-fuchsia-800
            dark:focus:data-[state=open]:bg-fuchsia-800`,
        pink: `text-pink-900
            hover:bg-pink-100
            hover:text-pink-900
            hover:border-pink-500
            focus:bg-pink-100
            focus:text-pink-900
            focus:border-pink-500
            data-[state=open]:bg-pink-100
            data-[disabled]:text-pink-700
            data-[state=open]:text-pink-900
            data-[state=open]:border-pink-500
            hover:data-[state=open]:bg-pink-200
            focus:data-[state=open]:bg-pink-200
            dark:text-pink-200
            dark:hover:bg-pink-900
            dark:hover:text-pink-100 
            dark:hover:border-pink-600 
            dark:focus:bg-pink-900 
            dark:focus:text-pink-100 
            dark:focus:border-pink-600
            dark:data-[state=open]:bg-pink-900 
            dark:data-[disabled]:text-pink-400
            dark:data-[state=open]:text-pink-100
            dark:data-[state=open]:border-pink-600
            dark:hover:data-[state=open]:bg-pink-800
            dark:focus:data-[state=open]:bg-pink-800`,
        rose: `text-rose-900
            hover:bg-rose-100
            hover:text-rose-900
            hover:border-rose-500
            focus:bg-rose-100
            focus:text-rose-900
            focus:border-rose-500
            data-[state=open]:bg-rose-100
            data-[disabled]:text-rose-700
            data-[state=open]:text-rose-900
            data-[state=open]:border-rose-500
            hover:data-[state=open]:bg-rose-200
            focus:data-[state=open]:bg-rose-200
            dark:text-rose-200
            dark:hover:bg-rose-900
            dark:hover:text-rose-100 
            dark:hover:border-rose-600 
            dark:focus:bg-rose-900 
            dark:focus:text-rose-100 
            dark:focus:border-rose-600
            dark:data-[state=open]:bg-rose-900 
            dark:data-[disabled]:text-rose-400
            dark:data-[state=open]:text-rose-100
            dark:data-[state=open]:border-rose-600
            dark:hover:data-[state=open]:bg-rose-800
            dark:focus:data-[state=open]:bg-rose-800`,
        "white-black": `text-neutral-900
            hover:bg-neutral-100
            hover:text-neutral-900
            hover:border-neutral-500
            focus:bg-neutral-100
            focus:text-neutral-900
            focus:border-neutral-500
            data-[state=open]:bg-neutral-100
            data-[disabled]:text-neutral-700
            data-[state=open]:text-neutral-900
            data-[state=open]:border-neutral-500
            hover:data-[state=open]:bg-neutral-200
            focus:data-[state=open]:bg-neutral-200
            dark:text-neutral-200
            dark:hover:bg-neutral-900
            dark:hover:text-neutral-100 
            dark:hover:border-neutral-600 
            dark:focus:bg-neutral-900 
            dark:focus:text-neutral-100 
            dark:focus:border-neutral-600
            dark:data-[state=open]:bg-neutral-900 
            dark:data-[disabled]:text-neutral-400
            dark:data-[state=open]:text-neutral-100
            dark:data-[state=open]:border-neutral-600
            dark:hover:data-[state=open]:bg-neutral-800
            dark:focus:data-[state=open]:bg-neutral-800`,
      },
    },
  },
);

export { trigger };
